import { Patient } from "../types/Patient";
import { Record } from "../types/Record";

export const singlePatient: Patient = {
    id: '1',
    registration: '1001',
    fullName: "Lucas Andrade",
    socialName: "Luke",
    birthDate: "1990-04-12",
    gender: "Male",
    identification: "123.456.789-00",
    rg: "MG-12.345.678",
    age: 35,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    records: [
        {
            date: new Date("2025-01-12"),
            records: [
                {
                    id: '0',
                    author: 'Thalles Gonçalves',
                    content: `<h1>Meu Post</h1><p>Olá, este é um exemplo de <strong>texto em negrito</ strong>, <em>itálico </em>, <u>sublinhado</u> e uma lista: </p><ul><li>Item 1 </li><li>Item 2 </li></ul><p><a href="https://angular.io" target = "_blank"> Angular </a></p>`,
                    date: new Date(),
                }
            ],
        },
    ],
    address: {
        postalCode: "30140-110",
        region: "Centro-Sul",
        state: "MG",
        neighborhood: "Savassi",
        city: "Belo Horizonte",
        street: "Rua Pernambuco",
        complement: "Apt 201",
        number: '1220',
    },
    phone: "(31) 3333-2222",
    cellphone: "(31) 99999-1234",
    email: "lucas.andrade@example.com",
    insuranceType: "Private",
    insuranceCode: "PRV123",
    cnsNumber: "12345678900",
    medicalRecordNumber: "MED001",
    tags: ["diabetes", "checkup"],
    registrationNumber: "REG001",
    company: "TechHealth",
    reference: "Dr. Marina Souza",
    referredBy: "Online",
    maritalStatus: "Single",
    profession: "Software Engineer",
    educationLevel: "Bachelor",
    fatherName: "Carlos Andrade",
    motherName: "Mariana Andrade",
    children: "0",
    companion: "",
    spouse: "",
    notes: "Allergic to penicillin.",
}

export const patientList: Patient[] = [
    {
        id: '1',
        registration: '1001',
        fullName: "Lucas Andrade",
        socialName: "Luke",
        birthDate: "1990-04-12",
        gender: "Male",
        identification: "123.456.789-00",
        rg: "MG-12.345.678",
        age: 35,
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        records: [
            {
                date: new Date("2025-01-12"),
                records: [],
            },
        ],
        address: {
            postalCode: "30140-110",
            region: "Centro-Sul",
            state: "MG",
            neighborhood: "Savassi",
            city: "Belo Horizonte",
            street: "Rua Pernambuco",
            complement: "Apt 201",
            number: '1220',
        },
        phone: "(31) 3333-2222",
        cellphone: "(31) 99999-1234",
        email: "lucas.andrade@example.com",
        insuranceType: "Private",
        insuranceCode: "PRV123",
        cnsNumber: "12345678900",
        medicalRecordNumber: "MED001",
        tags: ["diabetes", "checkup"],
        registrationNumber: "REG001",
        company: "TechHealth",
        reference: "Dr. Marina Souza",
        referredBy: "Online",
        maritalStatus: "Single",
        profession: "Software Engineer",
        educationLevel: "Bachelor",
        fatherName: "Carlos Andrade",
        motherName: "Mariana Andrade",
        children: "0",
        companion: "",
        spouse: "",
        notes: "Allergic to penicillin.",
    },
    {
        id: '2',
        registration: '1002',
        fullName: "Mariana Ribeiro",
        birthDate: "1987-09-22",
        gender: "Female",
        identification: "987.654.321-00",
        rg: "SP-45.678.910",
        age: 38,
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        records: [],
        address: {
            postalCode: "04538-132",
            region: "Sul",
            state: "SP",
            neighborhood: "Itaim Bibi",
            city: "São Paulo",
            street: "Rua Joaquim Floriano",
            complement: "Office 504",
            number: '466',
        },
        phone: "(11) 3456-7890",
        cellphone: "(11) 98888-1234",
        email: "mariana.ribeiro@example.com",
        insuranceType: "Public",
        insuranceCode: "SUS987",
        cnsNumber: "09876543211",
        medicalRecordNumber: "MED002",
        tags: ["hypertension"],
        registrationNumber: "REG002",
        company: "Hospital Vida",
        reference: "Dr. Paulo Lima",
        referredBy: "Friend",
        maritalStatus: "Married",
        profession: "Nurse",
        educationLevel: "Graduate",
        fatherName: "João Ribeiro",
        motherName: "Teresa Ribeiro",
        children: "2",
        companion: "",
        spouse: "Carlos Ribeiro",
        notes: "",
    },
    {
        id: '3',
        registration: '1003',
        fullName: "Pedro Silva",
        birthDate: "1995-11-05",
        gender: "Male",
        identification: "456.789.123-00",
        rg: "RJ-23.456.789",
        age: 30,
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        records: [],
        address: {
            postalCode: "22290-010",
            region: "Zona Sul",
            state: "RJ",
            neighborhood: "Botafogo",
            city: "Rio de Janeiro",
            street: "Rua São Clemente",
            complement: "",
            number: '200',
        },
        phone: "(21) 3333-4444",
        cellphone: "(21) 98888-5566",
        email: "pedro.silva@example.com",
        insuranceType: "Private",
        insuranceCode: "PRV456",
        cnsNumber: "55555555555",
        medicalRecordNumber: "MED003",
        tags: ["asthma"],
        registrationNumber: "REG003",
        company: "DataRio",
        reference: "Dr. Beatriz Mendes",
        referredBy: "Clinic",
        maritalStatus: "Single",
        profession: "Data Analyst",
        educationLevel: "Bachelor",
        fatherName: "José Silva",
        motherName: "Ana Silva",
        children: "0",
        companion: "",
        spouse: "",
        notes: "",
    },
    {
        id: '4',
        registration: '1004',
        fullName: "Fernanda Costa",
        birthDate: "1992-06-10",
        gender: "Female",
        identification: "321.654.987-00",
        rg: "PR-11.222.333",
        age: 33,
        image: "https://randomuser.me/api/portraits/women/4.jpg",
        records: [],
        address: {
            postalCode: "80010-000",
            region: "Centro",
            state: "PR",
            neighborhood: "Centro",
            city: "Curitiba",
            street: "Rua XV de Novembro",
            complement: "",
            number: '1100',
        },
        cellphone: "(41) 97777-2233",
        email: "fernanda.costa@example.com",
        insuranceType: "Private",
        insuranceCode: "PRV789",
        cnsNumber: "11122334455",
        medicalRecordNumber: "MED004",
        tags: [],
        registrationNumber: "REG004",
        company: "ClinVida",
        reference: "",
        referredBy: "Instagram",
        maritalStatus: "Divorced",
        profession: "Designer",
        educationLevel: "Bachelor",
        fatherName: "Marcos Costa",
        motherName: "Helena Costa",
        children: "1",
        companion: "",
        spouse: "",
        notes: "Uses contact lenses.",
    },
    {
        id: '5',
        registration: '1005',
        fullName: "Rafael Lima",
        birthDate: "1980-02-19",
        gender: "Male",
        identification: "222.333.444-55",
        rg: "RS-44.555.666",
        age: 45,
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        records: [],
        address: {
            postalCode: "90010-200",
            region: "Centro",
            state: "RS",
            neighborhood: "Centro Histórico",
            city: "Porto Alegre",
            street: "Av. Borges de Medeiros",
            complement: "Sala 301",
            number: '550',
        },
        cellphone: "(51) 99999-2233",
        email: "rafael.lima@example.com",
        insuranceType: "Public",
        insuranceCode: "SUS1234",
        cnsNumber: "98765432109",
        medicalRecordNumber: "MED005",
        tags: ["diabetes"],
        registrationNumber: "REG005",
        company: "AutoSul",
        maritalStatus: "Married",
        profession: "Mechanic",
        educationLevel: "High School",
        fatherName: "Fernando Lima",
        motherName: "Lucia Lima",
        children: "3",
        spouse: "Juliana Lima",
        notes: "",
    },
    {
        id: '6',
        registration: '1006',
        fullName: "Juliana Alves",
        birthDate: "1998-01-30",
        gender: "Female",
        identification: "333.222.111-00",
        rg: "BA-77.888.999",
        age: 27,
        image: "https://randomuser.me/api/portraits/women/6.jpg",
        records: [],
        address: {
            postalCode: "40015-150",
            region: "Sul",
            state: "BA",
            neighborhood: "Comércio",
            city: "Salvador",
            street: "Rua Chile",
            complement: "",
            number: '85',
        },
        cellphone: "(71) 91234-5678",
        email: "juliana.alves@example.com",
        insuranceType: "Private",
        insuranceCode: "PRV222",
        cnsNumber: "44455566677",
        medicalRecordNumber: "MED006",
        tags: [],
        registrationNumber: "REG006",
        maritalStatus: "Single",
        profession: "Lawyer",
        educationLevel: "Master",
        fatherName: "Eduardo Alves",
        motherName: "Patrícia Alves",
        children: "0",
        notes: "",
    },
    {
        id: '7',
        registration: '1007',
        fullName: "Thiago Martins",
        birthDate: "1993-03-18",
        gender: "Male",
        identification: "111.444.777-22",
        rg: "SC-33.222.111",
        age: 32,
        image: "https://randomuser.me/api/portraits/men/7.jpg",
        records: [],
        address: {
            postalCode: "88010-100",
            region: "Centro",
            state: "SC",
            neighborhood: "Centro",
            city: "Florianópolis",
            street: "Rua Felipe Schmidt",
            complement: "",
            number: '999',
        },
        cellphone: "(48) 98877-6655",
        email: "thiago.martins@example.com",
        insuranceType: "Private",
        insuranceCode: "PRV333",
        cnsNumber: "11122233344",
        medicalRecordNumber: "MED007",
        tags: ["sports"],
        registrationNumber: "REG007",
        profession: "Architect",
        educationLevel: "Bachelor",
        fatherName: "Ricardo Martins",
        motherName: "Carla Martins",
        notes: "",
    },
    {
        id: '8',
        registration: '1008',
        fullName: "Camila Duarte",
        birthDate: "1985-08-08",
        gender: "Female",
        identification: "555.666.777-88",
        rg: "CE-12.987.654",
        age: 40,
        image: "https://randomuser.me/api/portraits/women/8.jpg",
        records: [],
        address: {
            postalCode: "60115-001",
            region: "Leste",
            state: "CE",
            neighborhood: "Aldeota",
            city: "Fortaleza",
            street: "Av. Santos Dumont",
            complement: "",
            number: '1500',
        },
        cellphone: "(85) 98888-2233",
        email: "camila.duarte@example.com",
        insuranceType: "Public",
        insuranceCode: "SUS555",
        cnsNumber: "88899900011",
        medicalRecordNumber: "MED008",
        tags: [],
        registrationNumber: "REG008",
        maritalStatus: "Married",
        profession: "Teacher",
        educationLevel: "Master",
        fatherName: "Roberto Duarte",
        motherName: "Elisa Duarte",
        spouse: "Rodrigo Duarte",
        children: "2",
        notes: "Frequent migraines.",
    },
    {
        id: '9',
        registration: '1009',
        fullName: "Gabriel Rocha",
        birthDate: "1999-12-25",
        gender: "Male",
        identification: "888.999.111-22",
        rg: "DF-09.876.543",
        age: 25,
        image: "https://randomuser.me/api/portraits/men/9.jpg",
        records: [],
        address: {
            postalCode: "70040-010",
            region: "Centro",
            state: "DF",
            neighborhood: "Asa Sul",
            city: "Brasília",
            street: "SCS Quadra 2",
            complement: "",
            number: '150',
        },
        cellphone: "(61) 91111-2233",
        email: "gabriel.rocha@example.com",
        insuranceType: "Private",
        insuranceCode: "PRV444",
        cnsNumber: "99988877766",
        medicalRecordNumber: "MED009",
        registrationNumber: "REG009",
        profession: "Student",
        educationLevel: "Undergraduate",
        fatherName: "Paulo Rocha",
        motherName: "Cecília Rocha",
        notes: "",
    },
    {
        id: '10',
        registration: '1010',
        fullName: "Larissa Pires",
        birthDate: "1975-05-03",
        gender: "Female",
        identification: "999.888.777-00",
        rg: "PE-55.444.333",
        age: 50,
        image: "https://randomuser.me/api/portraits/women/10.jpg",
        records: [],
        address: {
            postalCode: "50030-000",
            region: "Centro",
            state: "PE",
            neighborhood: "Boa Vista",
            city: "Recife",
            street: "Rua da Aurora",
            complement: "",
            number: '122',
        },
        cellphone: "(81) 98877-1122",
        email: "larissa.pires@example.com",
        insuranceType: "Public",
        insuranceCode: "SUS222",
        cnsNumber: "44433322211",
        medicalRecordNumber: "MED010",
        registrationNumber: "REG010",
        maritalStatus: "Widowed",
        profession: "Doctor",
        educationLevel: "PhD",
        fatherName: "Otávio Pires",
        motherName: "Renata Pires",
        notes: "History of heart issues.",
    }
]

export const patientRecord: Record[] = [
    {
        id: '0',
        author: 'Thalles Gonçalves',
        content: 'Paciente retornando após consulta e cirurgia, aparenta normalidade e estabilidade com relação a dores localizadas e inchaços.',
        date: new Date(),
    }
]